# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Search-NCBI-PubMed
version:      0.01
version_from: lib/WWW/Search/NCBI/PubMed.pm
installdirs:  site
requires:
    File::Basename:                2.72
    Getopt::Long:                  0
    HTML::Entities:                0
    IO::Extended:                  0.08
    LWP::UserAgent:                0
    Path::Class:                   0.06
    Pod::Usage:                    0
    URI:                           0
    WWW::Search:                   0
    XML::LibXML:                   0
    XML::LibXSLT:                  0
    XML::XPath:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
